config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'quotes#index'
  resources :quotes
  get 'all', to: 'quotes#all'
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :saying, presence: true, length: { maximum: 300, minimum: 10 }
  validates :author, presence: true, length: { maximum: 50, minimum: 3 }
  validates :book, presence: true, length: { maximum: 100, minimum: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  
  def index
    @quote = Quote.order("Random()").first
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.create(quote_params)
      if @quote.invalid?
        flash[:error] = '<strong>Could not save</strong> the data you entered is invalid.'
      end
    redirect_to root_path
  end

  def all
    @quote = Quote.all 
  end

  private

  def quote_params
    params.require(:quote).permit(:saying, :author, :book)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Literbug</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="row">
      <div class="col-3">
        <%= link_to root_path, class: 'logo' do %>
          <div class="circle">
            <br />
            <br />
            Literbug
            <br />
          </div>
        <% end %>
      </div>
      <div class="col-4 slogan">
        Quotes that feel like home
      </div>
      <div class="col-4 links">
        <ul style="list-style: none;">
          <li><%= link_to 'Add a Quote', new_quote_path %></li>
          <li><%= link_to 'All Quotes', all_path %></li>
        </ul>
      </div>
    </header>

    <hr />   

    <br class="clear" />

  <div class="container">
    <% if flash[:error].present? %>
      <div class="col-10 offset-1 alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
    <% end %>
    
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>


    <%= yield %>
  </div>
    
  </body>
</html>

app/views/quotes/all.html.erb
<h1 class="library">Quote Library</h1>
<br />
<br />

<h2><% @quote.each do |quote| %>
  <div class="quote-box">
    <h1 class="saying"><%= quote.saying %></h1>
    <h2 class="author">- <%= quote.author %></h2>
    <h3 class="book"> <%= quote.book %></h3>
  </div>

  <br />
<% end %>

app/views/quotes/index.html.erb
<h1><%= @quote.saying %></h1>
<h2>- <%= @quote.author %>, <%= @quote.book%></h2>

app/views/quotes/new.html.erb
<h1>Enter Your Quote Details</h1>
<%= simple_form_for @quote do |f| %>
  <%= f.input :saying %>
  <%= f.input :author %>
  <%= f.input :book %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>